name: CPU Operation Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cpu_op_tests_linux:
    name: CPU Op Tests (Linux)
    runs-on: ubuntu-22.04

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build test-backend-ops
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DGGML_NATIVE=OFF \
            -DGGML_CPU_ALL_VARIANTS=ON \
            -DLLAMA_BUILD_TESTS=ON
          cmake --build build --config Release -j $(nproc) --target test-backend-ops

      - name: Run CPU op tests
        run: |
          cd build
          ctest -R test-backend-ops --output-on-failure --verbose

  cpu_op_tests_macos:
    name: CPU Op Tests (macOS)
    runs-on: macos-14

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build test-backend-ops
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DGGML_NATIVE=OFF \
            -DLLAMA_BUILD_TESTS=ON
          cmake --build build --config Release -j $(sysctl -n hw.logicalcpu) --target test-backend-ops

      - name: Run CPU op tests
        run: |
          cd build
          ctest -R test-backend-ops --output-on-failure --verbose

  cpu_op_tests_windows:
    name: CPU Op Tests (Windows)
    runs-on: windows-2025

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ninja
        run: choco install ninja

      - name: Build test-backend-ops
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -S . -B build -G "Ninja Multi-Config" ^
            -DGGML_NATIVE=OFF ^
            -DGGML_CPU_ALL_VARIANTS=ON ^
            -DGGML_OPENMP=ON ^
            -DLLAMA_BUILD_TESTS=ON
          cmake --build build --config Release --target test-backend-ops

      - name: Run CPU op tests
        run: |
          cd build
          ctest -C Release -R test-backend-ops --output-on-failure --verbose
